### ISSUE TITLE
Streaming.py gives an error regarding dotenv

### ISSUE THREAD

**Issue by techguysimon** [joeldg/bowhead#3]
Traceback (most recent call last):
  File "streaming.py", line 90, in <module>
    main()
  File "streaming.py", line 86, in main
    demo(displayHeartbeat)
  File "streaming.py", line 56, in demo
    response = connect_to_stream()
  File "streaming.py", line 28, in connect_to_stream
    dotenv.load()
AttributeError: 'module' object has no attribute 'load'

Any idea of how to fix this? I have attempted on my Mac and on an Ubuntu VPS

**Comment by joeldg** [comment]
I made this tons easier
See the Docker section
https://medium.com/@joeldg/an-advanced-tutorial-a-new-crypto-currency-trading-bot-boilerplate-framework-e777733607ae

Joel De Gan

**Comment by JeppeKnockaert** [comment]
You probably installed the wrong dotenv for python. I had the same issue, it was resolved by uninstalling my previously installed dotenv and using this command (as described in the readme): `pip install python-env`.
